# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20161002_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayAlias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shortid', hsreplaynet.utils.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True, verbose_name='Short ID')),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='games.GameReplay')),
            ],
        ),
    ]
