# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hearthstone.enums
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20161010_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('player_class', hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'INVALID'), (1, 'DEATHKNIGHT'), (2, 'DRUID'), (3, 'HUNTER'), (4, 'MAGE'), (5, 'PALADIN'), (6, 'PRIEST'), (7, 'ROGUE'), (8, 'SHAMAN'), (9, 'WARLOCK'), (10, 'WARRIOR'), (11, 'DREAM'), (12, 'NEUTRAL')], default=0, validators=[hsreplaynet.utils.fields.IntEnumValidator(hearthstone.enums.CardClass)])),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalDeck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('format', hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'FT_UNKNOWN'), (1, 'FT_WILD'), (2, 'FT_STANDARD')], default=0, validators=[hsreplaynet.utils.fields.IntEnumValidator(hearthstone.enums.FormatType)])),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_decks', to='cards.Archetype')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_for_archetypes', to='cards.Deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='archetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.Archetype'),
        ),
    ]
