# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_exclude_from_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joust_autoplay',
            field=models.BooleanField(default=True),
        ),
    ]
